### ISSUE TITLE
COATS_CLOSED / COATS Are the same ?

### ISSUE THREAD

**Issue by JaroSound** [VORPCORE/VORP-ClothingStore#3]
COATS_CLOSED / COATS Are the same for me when enter the shop On Male Model.

**Comment by BulgaRpl** [comment]
https://github.com/VORPCORE/VORP-ClothingStore/pull/4

**Comment by Artzalez** [comment]
https://github.com/VORPCORE/VORP-ClothingStore/releases/tag/JohnMarston
